### ISSUE TITLE
webfx bump cli error mesage

### ISSUE THREAD

**Issue by CommonGrounds** [webfx-project/webfx-cli#12]
$webfx bump cli

A new version is available!
Old version: 0.1.0-SNAPSHOT ~ 2024-01-07 13:34 GMT
[ERROR] COMPILATION ERROR : 
[ERROR] /home/ryzen/IntelliJ_IDEA/FrameWorks/WebFX/webfx-cli-main/src/main/java/dev/webfx/cli/sourcegenerators/RootConfigFileGenerator.java:[15,41] package dev.webfx.platform.util.keyobject does not exist
[ERROR] /home/ryzen/IntelliJ_IDEA/FrameWorks/WebFX/webfx-cli-main/src/main/java/dev/webfx/cli/sourcegenerators/RootConfigFileGenerator.java:[16,41] package dev.webfx.platform.util.keyobject does not exist
[ERROR] /home/ryzen/IntelliJ_IDEA/FrameWorks/WebFX/webfx-cli-main/src/main/java/dev/webfx/cli/sourcegenerators/RootConfigFileGenerator.java:[17,51] package dev.webfx.platform.util.keyobject.formatter does not exist
[ERROR] /home/ryzen/IntelliJ_IDEA/FrameWorks/WebFX/webfx-cli-main/src/main/java/dev/webfx/cli/sourcegenerators/RootConfigFileGenerator.java:[151,37] cannot find symbol
[ERROR] /home/ryzen/IntelliJ_IDEA/FrameWorks/WebFX/webfx-cli-main/src/main/java/dev/webfx/cli/sourcegenerators/RootConfigFileGenerator.java:[162,68] cannot find symbol
[ERROR] /home/ryzen/IntelliJ_IDEA/FrameWorks/WebFX/webfx-cli-main/src/main/java/dev/webfx/cli/sourcegenerators/RootConfigFileGenerator.java:[95,41] cannot find symbol
[ERROR] /home/ryzen/IntelliJ_IDEA/FrameWorks/WebFX/webfx-cli-main/src/main/java/dev/webfx/cli/sourcegenerators/RootConfigFileGenerator.java:[138,27] cannot find symbol
[ERROR] /home/ryzen/IntelliJ_IDEA/FrameWorks/WebFX/webfx-cli-main/src/main/java/dev/webfx/cli/sourcegenerators/RootConfigFileGenerator.java:[154,34] cannot find symbol
[ERROR] /home/ryzen/IntelliJ_IDEA/FrameWorks/WebFX/webfx-cli-main/src/main/java/dev/webfx/cli/sourcegenerators/RootConfigFileGenerator.java:[156,34] cannot find symbol
[ERROR] /home/ryzen/IntelliJ_IDEA/FrameWorks/WebFX/webfx-cli-main/src/main/java/dev/webfx/cli/sourcegenerators/RootConfigFileGenerator.java:[156,65] cannot find symbol
[ERROR] /home/ryzen/IntelliJ_IDEA/FrameWorks/WebFX/webfx-cli-main/src/main/java/dev/webfx/cli/sourcegenerators/RootConfigFileGenerator.java:[163,9] cannot find symbol
[ERROR] /home/ryzen/IntelliJ_IDEA/FrameWorks/WebFX/webfx-cli-main/src/main/java/dev/webfx/cli/sourcegenerators/RootConfigFileGenerator.java:[168,30] cannot find symbol
[ERROR] /home/ryzen/IntelliJ_IDEA/FrameWorks/WebFX/webfx-cli-main/src/main/java/dev/webfx/cli/sourcegenerators/RootConfigFileGenerator.java:[169,57] cannot find symbol
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.11.0:compile (default-compile) on project webfx-cli: Compilation failure: Compilation failure: 
[ERROR] /home/ryzen/IntelliJ_IDEA/FrameWorks/WebFX/webfx-cli-main/src/main/java/dev/webfx/cli/sourcegenerators/RootConfigFileGenerator.java:[15,41] package dev.webfx.platform.util.keyobject does not exist
[ERROR] /home/ryzen/IntelliJ_IDEA/FrameWorks/WebFX/webfx-cli-main/src/main/java/dev/webfx/cli/sourcegenerators/RootConfigFileGenerator.java:[16,41] package dev.webfx.platform.util.keyobject does not exist
[ERROR] /home/ryzen/IntelliJ_IDEA/FrameWorks/WebFX/webfx-cli-main/src/main/java/dev/webfx/cli/sourcegenerators/RootConfigFileGenerator.java:[17,51] package dev.webfx.platform.util.keyobject.formatter does not exist
[ERROR] /home/ryzen/IntelliJ_IDEA/FrameWorks/WebFX/webfx-cli-main/src/main/java/dev/webfx/cli/sourcegenerators/RootConfigFileGenerator.java:[151,37] cannot find symbol
[ERROR]   symbol:   class ReadOnlyKeyObject
[ERROR]   location: class dev.webfx.cli.sourcegenerators.RootConfigFileGenerator
[ERROR] /home/ryzen/IntelliJ_IDEA/FrameWorks/WebFX/webfx-cli-main/src/main/java/dev/webfx/cli/sourcegenerators/RootConfigFileGenerator.java:[162,68] cannot find symbol
[ERROR]   symbol:   class ReadOnlyKeyObject
[ERROR]   location: class dev.webfx.cli.sourcegenerators.RootConfigFileGenerator
[ERROR] /home/ryzen/IntelliJ_IDEA/FrameWorks/WebFX/webfx-cli-main/src/main/java/dev/webfx/cli/sourcegenerators/RootConfigFileGenerator.java:[95,41] cannot find symbol
[ERROR]   symbol:   class ReadOnlyIndexedArray
[ERROR]   location: class dev.webfx.cli.sourcegenerators.RootConfigFileGenerator
[ERROR] /home/ryzen/IntelliJ_IDEA/FrameWorks/WebFX/webfx-cli-main/src/main/java/dev/webfx/cli/sourcegenerators/RootConfigFileGenerator.java:[138,27] cannot find symbol
[ERROR]   symbol:   variable AstFormatter
[ERROR]   location: class dev.webfx.cli.sourcegenerators.RootConfigFileGenerator
[ERROR] /home/ryzen/IntelliJ_IDEA/FrameWorks/WebFX/webfx-cli-main/src/main/java/dev/webfx/cli/sourcegenerators/RootConfigFileGenerator.java:[154,34] cannot find symbol
[ERROR]   symbol:   class ReadOnlyIndexedArray
[ERROR]   location: class dev.webfx.cli.sourcegenerators.RootConfigFileGenerator
[ERROR] /home/ryzen/IntelliJ_IDEA/FrameWorks/WebFX/webfx-cli-main/src/main/java/dev/webfx/cli/sourcegenerators/RootConfigFileGenerator.java:[156,34] cannot find symbol
[ERROR]   symbol:   class ReadOnlyKeyObject
[ERROR]   location: class dev.webfx.cli.sourcegenerators.RootConfigFileGenerator
[ERROR] /home/ryzen/IntelliJ_IDEA/FrameWorks/WebFX/webfx-cli-main/src/main/java/dev/webfx/cli/sourcegenerators/RootConfigFileGenerator.java:[156,65] cannot find symbol
[ERROR]   symbol:   class ReadOnlyKeyObject
[ERROR]   location: class dev.webfx.cli.sourcegenerators.RootConfigFileGenerator
[ERROR] /home/ryzen/IntelliJ_IDEA/FrameWorks/WebFX/webfx-cli-main/src/main/java/dev/webfx/cli/sourcegenerators/RootConfigFileGenerator.java:[163,9] cannot find symbol
[ERROR]   symbol:   class ReadOnlyIndexedArray
[ERROR]   location: class dev.webfx.cli.sourcegenerators.RootConfigFileGenerator
[ERROR] /home/ryzen/IntelliJ_IDEA/FrameWorks/WebFX/webfx-cli-main/src/main/java/dev/webfx/cli/sourcegenerators/RootConfigFileGenerator.java:[168,30] cannot find symbol
[ERROR]   symbol:   class ReadOnlyKeyObject
[ERROR]   location: class dev.webfx.cli.sourcegenerators.RootConfigFileGenerator
[ERROR] /home/ryzen/IntelliJ_IDEA/FrameWorks/WebFX/webfx-cli-main/src/main/java/dev/webfx/cli/sourcegenerators/RootConfigFileGenerator.java:[169,57] cannot find symbol
[ERROR]   symbol:   class ReadOnlyKeyObject
[ERROR]   location: class dev.webfx.cli.sourcegenerators.RootConfigFileGenerator

**Comment by salmonb** [comment]
Sorry you're experiencing this problem.

It's strange, because `webfx bump cli` does a `git pull`, which should let you get the latest version of the code, and as you can see the latest [RootConfigFileGenerator](https://github.com/webfx-project/webfx-cli/blob/main/src/main/java/dev/webfx/cli/sourcegenerators/RootConfigFileGenerator.java) doesn't import `dev.webfx.platform.util.keyobject` package anymore (as opposed to what the error says).

Maybe you can try to go to your webfx-cli clone repo and type `git pull` and then `mvn package`.

Let me know if that resolve the issue.
