### ISSUE TITLE
Prepare cli for webfx-maven-plugin

### ISSUE THREAD

**Issue by AlexBelchUK** [webfx-project/webfx-cli#5]
Couple of fixes for the CLI to compile
Plus change for the resource loading of XML files to work with class loader when run as maven plugin. 
Can you assign to me, I'll need to be able to create a branch and push for review thanks Alex belch

**Comment by salmonb** [comment]
That's great, thank you so much for contributing to the project.
Please open a PR instead.
I'm looking forward to reviewing it 🙂

**Comment by AlexBelchUK** [comment]
The web-cli and web-maven-plugin branches should now be ready to review. Hope it is all okay :-)

**Comment by salmonb** [comment]
Thanks for that. I commented your PR for the WebFX CLI, and wait for your reply before looking at the PR for the Maven plugin.

**Comment by salmonb** [comment]
I have closed the [PR](https://github.com/webfx-project/webfx-cli/pull/6) associated with the WebFX CLI, as the [PR](https://github.com/webfx-project/webfx-maven-plugin/pull/1) associated with the WebFX Maven plugin has now been successfully merged (thanks Alex!). This closes this issue.
